name: Delete Slack Messages
run-name: Delete Slack Messages (channel - ${{ inputs.channel }})
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'channel name to clear - set to ALL to clear all public channels'
        required: true
jobs:
  delete-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Delete messages
        run: node slack/deleteAllMessages.js ${{ github.event.inputs.channel }}
        env:
          SLACK_TOKEN_SEIOPR: ${{ secrets.SLACK_TOKEN_SEIOPR }}
          SLACK_TOKEN_HRSEIP: ${{ secrets.SLACK_TOKEN_HRSEIP }}
