name: New Student Onboarding
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 */2 * * *'
jobs:
  onboard-students:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
        
      - name: Onboard new students
        run: node tools/onboard.js
        env:
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GMAIL_CLIENT_EMAIL: ${{ secrets.GMAIL_CLIENT_EMAIL }}
          GMAIL_PRIVATE_KEY: ${{ secrets.GMAIL_PRIVATE_KEY }}
          SFDC_LOGIN_URL: ${{ secrets.SFDC_LOGIN_URL }}
          SFDC_USERNAME: ${{ secrets.SFDC_USERNAME }}
          SFDC_PASSWORD: ${{ secrets.SFDC_PASSWORD }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
          LEARN_TOKEN: ${{ secrets.LEARN_TOKEN }}
          SLACK_TOKEN_SEIOPR: ${{ secrets.SLACK_TOKEN_SEIOPR }}
          SLACK_TOKEN_HRSEIP: ${{ secrets.SLACK_TOKEN_HRSEIP }}
