name: Re-send GitHub Invites
on:
  workflow_dispatch: {}
  schedule:
    - cron: '5 */10 * * *'
jobs:
  resend-github-invites:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Re-send GitHub invites
        run: node tools/resendGitHubInvites.js
        env:
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
